version: "3.6"

services:

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: forever18
      MYSQL_DATABASE: travel_with_me
    networks:
      - employee-mysql

  server:
    build: .
    restart: on-failure
    depends_on:
      - database
    links:
      - database
    networks:
      - employee-mysql
    ports:
      - 9090:9090

networks:
  employee-mysql: